# Generated by Django 2.1.2 on 2018-10-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_validation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rfvalue',
            field=models.CharField(default='nil', max_length=20),
            preserve_default=False,
        ),
    ]
